services:
  viewer:
    build:
      context: .
      dockerfile: docker/viewer.Dockerfile
    container_name: traverse-viewer
    restart: unless-stopped
    ports:
      - 3004:3000
    volumes:
      - ./data:/app/data
