services:
  traverse:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: traverse
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./data:/app/data
